# Generated by Django 4.1.6 on 2023-02-18 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Roles', '0004_rename_created_roles_datetime_created_and_more'),
        ('Access_Page', '0008_remove_accesspage_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Page_Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('AccessPage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Access_Page.accesspage')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Roles.roles')),
            ],
        ),
    ]
