# Generated by Django 4.1.6 on 2023-02-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Access_Page', '0007_alter_accesspage_method_alter_accesspage_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspage',
            name='role',
        ),
    ]
