# Generated by Django 4.1.6 on 2023-02-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
