# Generated by Django 4.1.6 on 2023-02-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0002_alter_roles_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
