# Generated by Django 4.1.6 on 2023-02-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0003_roles_created_roles_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='updated',
            new_name='datetime_updated',
        ),
    ]
